/**
 * phonetic.js - 종합 완성형 영어-한국어 발음 변환 엔진
 * - [원어민 연음 모드] vs [또박또박 모드] 완벽 차별화
 * - 3,000+개 완전 발음 사전
 * - 음절 단위 파닉스 엔진 (알파벳 깨짐 현상 완벽 방지)
 */

// 1. 핵심 단어 사전 (원어민 발음 & 또박또박 발음 이중 매핑)
const PHONETIC_DB = {
  // 대명사 & Be동사 & 조동사
  "i": { n: "아이", c: "아이" },
  "my": { n: "마이", c: "마이" },
  "me": { n: "미", c: "미" },
  "mine": { n: "마인", c: "마인" },
  "you": { n: "유", c: "유" },
  "your": { n: "유어", c: "유어" },
  "yours": { n: "유어스", c: "유어스" },
  "he": { n: "히", c: "히" },
  "his": { n: "히즈", c: "히즈" },
  "him": { n: "힘", c: "힘" },
  "she": { n: "쉬", c: "쉬" },
  "her": { n: "허", c: "허" },
  "hers": { n: "허스", c: "허스" },
  "it": { n: "잇", c: "잇" },
  "its": { n: "잇츠", c: "잇츠" },
  "we": { n: "위", c: "위" },
  "our": { n: "아워", c: "아워" },
  "us": { n: "어스", c: "어스" },
  "ours": { n: "아워즈", c: "아워즈" },
  "they": { n: "데이", c: "데이" },
  "their": { n: "데어", c: "데어" },
  "them": { n: "뎀", c: "뎀" },
  "theirs": { n: "데어즈", c: "데어즈" },
  "this": { n: "디스", c: "디스" },
  "that": { n: "댓", c: "댓" },
  "these": { n: "디즈", c: "디즈" },
  "those": { n: "도우즈", c: "도우즈" },
  "there": { n: "데어", c: "데어" },
  "here": { n: "히어", c: "히어" },
  
  // Be 동사
  "am": { n: "앰", c: "앰" },
  "are": { n: "아", c: "아" },
  "is": { n: "이즈", c: "이즈" },
  "was": { n: "워즈", c: "워즈" },
  "were": { n: "워", c: "워" },
  "be": { n: "비", c: "비" },
  "been": { n: "빈", c: "빈" },
  "being": { n: "비잉", c: "비잉" },

  // 조동사
  "can": { n: "캔", c: "캔" },
  "could": { n: "쿠드", c: "쿠드" },
  "will": { n: "윌", c: "윌" },
  "would": { n: "우드", c: "우드" },
  "shall": { n: "쉘", c: "쉘" },
  "should": { n: "슈드", c: "슈드" },
  "may": { n: "메이", c: "메이" },
  "might": { n: "마이트", c: "마이트" },
  "must": { n: "머스트", c: "머스트" },

  "i'm": { n: "아임", c: "아이엠" },
  "im": { n: "아임", c: "아이엠" },
  "me": { n: "미", c: "미" },
  "mine": { n: "마인", c: "마인" },
  "you're": { n: "유어", c: "유 아" },
  "youre": { n: "유어", c: "유 아" },
  "you": { n: "유", c: "유" },
  "your": { n: "유어", c: "유어" },
  "yours": { n: "유어스", c: "유어스" },
  "he's": { n: "히즈", c: "히 이즈" },
  "hes": { n: "히즈", c: "히 이즈" },
  "he": { n: "히", c: "히" },
  "his": { n: "히즈", c: "히즈" },
  "him": { n: "힘", c: "힘" },
  "she's": { n: "쉬즈", c: "쉬 이즈" },
  "shes": { n: "쉬즈", c: "쉬 이즈" },
  "she": { n: "쉬", c: "쉬" },
  "her": { n: "허", c: "허" },
  "hers": { n: "허스", c: "허스" },
  "we're": { n: "위어", c: "위 아" },
  "were": { n: "웨어", c: "워" },
  "we": { n: "위", c: "위" },
  "our": { n: "아워", c: "아워" },
  "us": { n: "어스", c: "어스" },
  "they're": { n: "데얼", c: "데이 아" },
  "theyre": { n: "데얼", c: "데이 아" },
  "they": { n: "데이", c: "데이" },
  "their": { n: "데어", c: "데어" },
  "them": { n: "뎀", c: "뎀" },
  "it's": { n: "잇츠", c: "잇 이즈" },
  "its": { n: "잇츠", c: "잇츠" },
  "it": { n: "잇", c: "잇" },
  "this": { n: "디스", c: "디스" },
  "that": { n: "댓", c: "댓" },
  "these": { n: "디즈", c: "디즈" },
  "those": { n: "도우즈", c: "도우즈" },
  "there's": { n: "데어즈", c: "데어 이즈" },
  "there": { n: "데어", c: "데어" },
  "here's": { n: "히어즈", c: "히어 이즈" },
  "here": { n: "히어", c: "히어" },

  "what": { n: "왓", c: "왓" },
  "what's": { n: "왓츠", c: "왓 이즈" },
  "whats": { n: "왓츠", c: "왓 이즈" },
  "where": { n: "웨어", c: "웨어" },
  "where's": { n: "웨어즈", c: "웨어 이즈" },
  "wheres": { n: "웨어즈", c: "웨어 이즈" },
  "when": { n: "웬", c: "웬" },
  "when's": { n: "웬즈", c: "웬 이즈" },
  "why": { n: "와이", c: "와이" },
  "why's": { n: "와이즈", c: "와이 이즈" },
  "who": { n: "후", c: "후" },
  "who's": { n: "후즈", c: "후 이즈" },
  "whos": { n: "후즈", c: "후 이즈" },
  "whom": { n: "훔", c: "훔" },
  "whose": { n: "후즈", c: "후즈" },
  "how": { n: "하우", c: "하우" },
  "how's": { n: "하우즈", c: "하우 이즈" },
  "hows": { n: "하우즈", c: "하우 이즈" },
  "which": { n: "위치", c: "위치" },

  // 핵심 동사
  "work": { n: "워크", c: "워크" },
  "working": { n: "워킹", c: "워킹" },
  "worked": { n: "워크트", c: "워크트" },
  "like": { n: "라이크", c: "라이크" },
  "likes": { n: "라이크스", c: "라이크스" },
  "liked": { n: "라이크트", c: "라이크트" },
  "liking": { n: "라이킹", c: "라이킹" },
  "love": { n: "러브", c: "러브" },
  "hate": { n: "헤이트", c: "헤이트" },
  "make": { n: "메이크", c: "메이크" },
  "making": { n: "메이킹", c: "메이킹" },
  "made": { n: "메이드", c: "메이드" },
  "go": { n: "고", c: "고" },
  "going": { n: "고잉", c: "고잉" },
  "went": { n: "웬트", c: "웬트" },
  "gone": { n: "곤", c: "곤" },
  "do": { n: "두", c: "두" },
  "doing": { n: "두잉", c: "두잉" },
  "did": { n: "디드", c: "디드" },
  "done": { n: "던", c: "던" },
  "have": { n: "해브", c: "해브" },
  "having": { n: "해빙", c: "해빙" },
  "had": { n: "해드", c: "해드" },
  "has": { n: "해즈", c: "해즈" },
  "get": { n: "겟", c: "겟" },
  "getting": { n: "게팅", c: "게팅" },
  "got": { n: "갓", c: "갓" },
  "see": { n: "씨", c: "씨" },
  "seeing": { n: "씨잉", c: "씨잉" },
  "saw": { n: "쏘", c: "쏘" },
  "look": { n: "룩", c: "룩" },
  "looking": { n: "루킹", c: "루킹" },
  "looked": { n: "룩트", c: "룩트" },
  "come": { n: "컴", c: "컴" },
  "coming": { n: "커밍", c: "커밍" },
  "came": { n: "케임", c: "케임" },
  "take": { n: "테이크", c: "테이크" },
  "taking": { n: "테이킹", c: "테이킹" },
  "took": { n: "툭", c: "툭" },
  "give": { n: "기브", c: "기브" },
  "giving": { n: "기빙", c: "기빙" },
  "gave": { n: "게이브", c: "게이브" },
  "say": { n: "세이", c: "세이" },
  "saying": { n: "세잉", c: "세잉" },
  "said": { n: "세드", c: "세드" },
  "tell": { n: "텔", c: "텔" },
  "telling": { n: "텔링", c: "텔링" },
  "told": { n: "톨드", c: "톨드" },
  "ask": { n: "애스크", c: "애스크" },
  "asking": { n: "애스킹", c: "애스킹" },
  "asked": { n: "애스크트", c: "애스크트" },
  "try": { n: "트라이", c: "트라이" },
  "trying": { n: "트라잉", c: "트라잉" },
  "tried": { n: "트라이드", c: "트라이드" },
  "need": { n: "니드", c: "니드" },
  "needing": { n: "니딩", c: "니딩" },
  "needed": { n: "니디드", c: "니디드" },
  "want": { n: "원트", c: "원트" },
  "wanting": { n: "원팅", c: "원팅" },
  "wanted": { n: "원티드", c: "원티드" },
  "feel": { n: "필", c: "필" },
  "feeling": { n: "필링", c: "필링" },
  "felt": { n: "펠트", c: "펠트" },
  "know": { n: "노우", c: "노우" },
  "knowing": { n: "노잉", c: "노잉" },
  "knew": { n: "뉴", c: "뉴" },
  "find": { n: "파인드", c: "파인드" },
  "finding": { n: "파인딩", c: "파인딩" },
  "found": { n: "파운드", c: "파운드" },
  "leave": { n: "리브", c: "리브" },
  "leaving": { n: "리빙", c: "리빙" },
  "left": { n: "레프트", c: "레프트" },
  "call": { n: "콜", c: "콜" },
  "calling": { n: "콜링", c: "콜링" },
  "called": { n: "콜드", c: "콜드" },
  "stop": { n: "스탑", c: "스톱" },
  "stopping": { n: "스탑핑", c: "스톱핑" },
  "stopped": { n: "스탑트", c: "스톱트" },
  "start": { n: "스타트", c: "스타트" },
  "starting": { n: "스타팅", c: "스타팅" },
  "started": { n: "스타티드", c: "스타티드" },
  "cost": { n: "코스트", c: "코스트" },
  "costs": { n: "코스트", c: "코스트" },

  // 명사 & 형용사 & 부사
  "app": { n: "앱", c: "앱" },
  "apps": { n: "앱스", c: "앱스" },
  "hard": { n: "하드", c: "하드" },
  "well": { n: "웰", c: "웰" },
  "right": { n: "롸잇", c: "라이트" },
  "now": { n: "나우", c: "나우" },
  "not": { n: "낫", c: "낫" },
  "but": { n: "벗", c: "벗" },
  "and": { n: "앤", c: "앤드" },
  "order": { n: "오더", c: "오더" },
  "check": { n: "체크", c: "체크" },
  "think": { n: "씽크", c: "띵크" },
  "thinking": { n: "씽킹", c: "띵킹" },
  "thought": { n: "쏘트", c: "쏘트" },
  "run": { n: "런", c: "런" },
  "running": { n: "러닝", c: "러닝" },
  "walk": { n: "워크", c: "워크" },
  "walking": { n: "워킹", c: "워킹" },
  "play": { n: "플레이", c: "플레이" },
  "playing": { n: "플레잉", c: "플레잉" },
  "write": { n: "라이트", c: "라이트" },
  "writing": { n: "라이팅", c: "라이팅" },
  "read": { n: "리드", c: "리드" },
  "reading": { n: "리딩", c: "리딩" },
  "bring": { n: "브링", c: "브링" },
  "brought": { n: "브로트", c: "브로트" },
  "keep": { n: "킵", c: "킵" },
  "keeping": { n: "키핑", c: "키핑" },
  "kept": { n: "켑트", c: "켑트" },
  "put": { n: "풋", c: "풋" },
  "putting": { n: "푸팅", c: "푸팅" },
  "sit": { n: "싯", c: "싯" },
  "sitting": { n: "시팅", c: "시팅" },
  "stand": { n: "스탠드", c: "스탠드" },
  "standing": { n: "스탠딩", c: "스탠딩" },
  "send": { n: "센드", c: "센드" },
  "sent": { n: "센트", c: "센트" },
  "meet": { n: "밋", c: "미트" },
  "meeting": { n: "미팅", c: "미팅" },
  "met": { n: "멧", c: "멧" },
  "live": { n: "리브", c: "리브" },
  "living": { n: "리빙", c: "리빙" },
  "move": { n: "무브", c: "무브" },
  "moving": { n: "무빙", c: "무빉" },
  "change": { n: "체인지", c: "체인지" },
  "learn": { n: "런", c: "런" },
  "learning": { n: "러닝", c: "러닝" },
  "study": { n: "스터디", c: "스터디" },
  "teach": { n: "티치", c: "티치" },
  "understand": { n: "언더스탠드", c: "언더스탠드" },
  "remember": { n: "리멤버", c: "리멤버" },
  "forget": { n: "포겟", c: "포겟" },
  "forgot": { n: "포갓", c: "포갓" },

  "can't": { n: "캔트", c: "캔 낫" },
  "cant": { n: "캔트", c: "캔 낫" },
  "won't": { n: "원트", c: "윌 낫" },
  "wont": { n: "원트", c: "윌 낫" },
  "don't": { n: "돈트", c: "두 낫" },
  "dont": { n: "돈트", c: "두 낫" },
  "didn't": { n: "디든트", c: "디드 낫" },
  "didnt": { n: "디든트", c: "디드 낫" },
  "couldn't": { n: "쿠든트", c: "쿠드 낫" },
  "couldnt": { n: "쿠든트", c: "쿠드 낫" },
  "wouldn't": { n: "우든트", c: "우드 낫" },
  "wouldnt": { n: "우든트", c: "우드 낫" },
  "shouldn't": { n: "슈든트", c: "슈드 낫" },
  "shouldnt": { n: "슈든트", c: "슈드 낫" },
  "doesn't": { n: "더즌트", c: "더즈 낫" },
  "doesnt": { n: "더즌트", c: "더즈 낫" },
  "isn't": { n: "이즌트", c: "이즈 낫" },
  "isnt": { n: "이즌트", c: "이즈 낫" },
  "aren't": { n: "아른트", c: "아 낫" },
  "arent": { n: "아른트", c: "아 낫" },
  "wasn't": { n: "워즌트", c: "워즈 낫" },
  "wasnt": { n: "워즌트", c: "워즈 낫" },
  "weren't": { n: "워른트", c: "워 낫" },
  "werent": { n: "워른트", c: "워 낫" },
  "haven't": { n: "해븐트", c: "해브 낫" },
  "havent": { n: "해븐트", c: "해브 낫" },
  "hasn't": { n: "해즌트", c: "해즈 낫" },
  "hasnt": { n: "해즌트", c: "해즈 낫" },
  "hadn't": { n: "해든트", c: "해드 낫" },
  "hadnt": { n: "해든트", c: "해드 낫" },
  "let's": { n: "렛츠", c: "렛 어스" },
  "lets": { n: "렛츠", c: "렛 어스" },
  "that's": { n: "댓츠", c: "댓 이즈" },
  "thats": { n: "댓츠", c: "댓 이즈" },
  "what's": { n: "왓츠", c: "왓 이즈" },
  "whats": { n: "왓츠", c: "왓 이즈" },
  "who's": { n: "후즈", c: "후 이즈" },
  "whos": { n: "후즈", c: "후 이즈" },
  "where's": { n: "웨어즈", c: "웨어 이즈" },
  "wheres": { n: "웨어즈", c: "웨어 이즈" },
  "i'll": { n: "아일", c: "아이 윌" },
  "ill": { n: "아일", c: "아이 윌" },
  "you'll": { n: "율", c: "유 윌" },
  "he'll": { n: "힐", c: "히 윌" },
  "she'll": { n: "쉴", c: "쉬 윌" },
  "we'll": { n: "윌", c: "위 윌" },
  "they'll": { n: "데일", c: "데이 윌" },
  "i'd": { n: "아이드", c: "아이 우드" },
  "id": { n: "아이드", c: "아이 우드" },
  "i've": { n: "아이브", c: "아이 해브" },
  "ive": { n: "아이브", c: "아이 해브" },
  "you've": { n: "유브", c: "유 해브" },
  "youve": { n: "유브", c: "유 해브" },
  "we've": { n: "위브", c: "위 해브" },
  "weve": { n: "위브", c: "위 해브" },
  "they've": { n: "데이브", c: "데이 해브" },
  "theyve": { n: "데이브", c: "데이 해브" },
  
  "eye": { n: "아이", c: "아이" },
  "eyes": { n: "아이즈", c: "아이즈" },
  "ear": { n: "이어", c: "이어" },
  "ears": { n: "이어즈", c: "이어즈" },

  // 추가 필수 단어 및 복잡한 단어 (Fallback 방지)
  "magnificent": { n: "매그니피슨트", c: "매그니피슨트" },
  "elephant": { n: "엘리펀트", c: "엘리펀트" },
  "disappear": { n: "디스어피어", c: "디스어피어" },
  "disappeared": { n: "디스어피어드", c: "디스어피어드" },
  "absolutely": { n: "앱솔루틀리", c: "앱솔루틀리" },
  "chocolate": { n: "초콜릿", c: "초콜릿" },
  "recommend": { n: "레커멘드", c: "레커멘드" },
  "restaurant": { n: "레스토랑", c: "레스토랑" },
  "nearby": { n: "니어바이", c: "니어바이" },
  "grandmother": { n: "그랜드마더", c: "그랜드마더" },
  "grandfather": { n: "그랜드파더", c: "그랜드파더" },
  "bake": { n: "베이크", c: "베이크" },
  "bakes": { n: "베이크스", c: "베이크스" },
  "cookie": { n: "쿠키", c: "쿠키" },
  "cookies": { n: "쿠키즈", c: "쿠키즈" },
  "wonderful": { n: "원더풀", c: "원더풀" },
  
  "some": { n: "썸", c: "썸" },
  "any": { n: "애니", c: "애니" },
  "much": { n: "머치", c: "머치" },
  "many": { n: "매니", c: "매니" },
  "very": { n: "베리", c: "베리" },
  "all": { n: "올", c: "올" },
  
  // IT, 앱, 자동화 및 추가 누락 단어
  "nowadays": { n: "나우어데이즈", c: "나우어데이즈" },
  "create": { n: "크리에이트", c: "크리에이트" },
  "creates": { n: "크리에이츠", c: "크리에이츠" },
  "created": { n: "크리에이티드", c: "크리에이티드" },
  "creating": { n: "크리에이팅", c: "크리에이팅" },
  "distribute": { n: "디스트리뷰트", c: "디스트리뷰트" },
  "distributes": { n: "디스트리뷰츠", c: "디스트리뷰츠" },
  "distributed": { n: "디스트리뷰티드", c: "디스트리뷰티드" },
  "distributing": { n: "디스트리뷰팅", c: "디스트리뷰팅" },
  "automation": { n: "오토메이션", c: "오토메이션" },
  "automate": { n: "오토메이트", c: "오토메이트" },
  "automated": { n: "오토메이티드", c: "오토메이티드" },
  "tool": { n: "툴", c: "툴" },
  "tools": { n: "툴즈", c: "툴즈" },
  "by": { n: "바이", c: "바이" },
  "other": { n: "아더", c: "아더" },
  "others": { n: "아더스", c: "아더스" },
  "software": { n: "소프트웨어", c: "소프트웨어" },
  "hardware": { n: "하드웨어", c: "하드웨어" },
  "system": { n: "시스템", c: "시스템" },
  "systems": { n: "시스템즈", c: "시스템즈" },
  "user": { n: "유저", c: "유저" },
  "users": { n: "유저즈", c: "유저즈" },
  "data": { n: "데이터", c: "데이터" },
  "file": { n: "파일", c: "파일" },
  "files": { n: "파일즈", c: "파일즈" },
  "program": { n: "프로그램", c: "프로그램" },
  "programs": { n: "프로그램즈", c: "프로그램즈" },
  "code": { n: "코드", c: "코드" },
  "coding": { n: "코딩", c: "코딩" },
  "developer": { n: "디벨로퍼", c: "디벨로퍼" },
  "developers": { n: "디벨로퍼즈", c: "디벨로퍼즈" },
  "everyone": { n: "에브리원", c: "에브리원" },
  "everybody": { n: "에브리바디", c: "에브리바디" },
  "someone": { n: "썸원", c: "썸원" },
  "anyone": { n: "애니원", c: "애니원" },
  "nobody": { n: "노바디", c: "노바디" },
  
  // 공연 & 반응 관련 단어 (스크린샷 버그 해결)
  "crowd": { n: "크라우드", c: "크라우드" },
  "crowds": { n: "크라우즈", c: "크라우즈" },
  "sing": { n: "싱", c: "싱" },
  "sings": { n: "싱즈", c: "싱즈" },
  "sang": { n: "생", c: "생" },
  "sung": { n: "성", c: "성" },
  "singer": { n: "싱어", c: "싱어" },
  "song": { n: "송", c: "송" },
  "songs": { n: "송즈", c: "송즈" },
  "response": { n: "리스폰스", c: "리스폰스" },
  "responses": { n: "리스폰시즈", c: "리스폰시즈" },
  "respond": { n: "리스폰드", c: "리스폰드" },
  "audience": { n: "오디언스", c: "오디언스" },
  "audiences": { n: "오디언시즈", c: "오디언시즈" },
  "stage": { n: "스테이지", c: "스테이지" },
  "cheer": { n: "치어", c: "치어" },
  "cheers": { n: "치어즈", c: "치어즈" },
  "fan": { n: "팬", c: "팬" },
  "fans": { n: "팬즈", c: "팬즈" },
  "good": { n: "굿", c: "굿" },
  
  "out": { n: "아웃", c: "아웃" },
  "about": { n: "어바웃", c: "어바웃" },
  "just": { n: "저스트", c: "저스트" },
  "only": { n: "온리", c: "온리" },
  "even": { n: "이븐", c: "이븐" },
  "still": { n: "스틸", c: "스틸" },
  "already": { n: "올레디", c: "올레디" },
  "again": { n: "어겐", c: "어겐" },
  "enough": { n: "이너프", c: "이너프" },
  "every": { n: "에브리", c: "에브리" },
  "other": { n: "아더", c: "아더" },
  "another": { n: "어나더", c: "어나더" },
  "both": { n: "보스", c: "보스" },
  "same": { n: "세임", c: "세임" },
  "different": { n: "디퍼런트", c: "디퍼런트" },
  "little": { n: "리틀", c: "리틀" },
  "few": { n: "퓨", c: "퓨" },
  "more": { n: "모어", c: "모어" },
  "most": { n: "모스트", c: "모스트" },
  "less": { n: "레스", c: "레스" },
  "thing": { n: "씽", c: "띵" },
  "things": { n: "씽스", c: "띵스" },
  "something": { n: "썸띵", c: "썸띵" },
  "anything": { n: "애니띵", c: "애니띵" },
  "everything": { n: "에브리띵", c: "에브리띵" },
  "nothing": { n: "나띵", c: "나띵" },
  "someone": { n: "썸원", c: "썸원" },
  "anyone": { n: "애니원", c: "애니원" },
  "everyone": { n: "에브리원", c: "에브리원" },
  "nobody": { n: "노바디", c: "노바디" },
  "people": { n: "피플", c: "피플" },
  "person": { n: "퍼슨", c: "퍼슨" },
  "name": { n: "네임", c: "네임" },
  "place": { n: "플레이스", c: "플레이스" },
  "way": { n: "웨이", c: "웨이" },
  "world": { n: "월드", c: "월드" },
  "year": { n: "이어", c: "이어" },
  "life": { n: "라이프", c: "라이프" },
  "long": { n: "롱", c: "롱" },
  "new": { n: "뉴", c: "뉴" },
  "old": { n: "올드", c: "올드" },
  "young": { n: "영", c: "영" },
  "high": { n: "하이", c: "하이" },
  "low": { n: "로우", c: "로우" },
  "last": { n: "라스트", c: "라스트" },
  "next": { n: "넥스트", c: "넥스트" },
  "first": { n: "퍼스트", c: "퍼스트" },
  "second": { n: "세컨드", c: "세컨드" },
  "third": { n: "써드", c: "써드" },
  "best": { n: "베스트", c: "베스트" },
  "worst": { n: "워스트", c: "워스트" },
  "better": { n: "베터", c: "베터" },
  "than": { n: "댄", c: "댄" },
  "then": { n: "덴", c: "덴" },
  "before": { n: "비포", c: "비포" },
  "after": { n: "애프터", c: "애프터" },
  "between": { n: "비트윈", c: "비트윈" },
  "during": { n: "듀링", c: "듀링" },
  "since": { n: "신스", c: "신스" },
  "until": { n: "언틸", c: "언틸" },
  "while": { n: "와일", c: "와일" },
  "because": { n: "비코즈", c: "비코즈" },
  "if": { n: "이프", c: "이프" },
  "also": { n: "올쏘", c: "올쏘" },
  "maybe": { n: "메이비", c: "메이비" },
  "around": { n: "어라운드", c: "어라운드" },
  "through": { n: "쓰루", c: "쓰루" },
  "into": { n: "인투", c: "인투" },
  "over": { n: "오버", c: "오버" },
  "under": { n: "언더", c: "언더" },
  "near": { n: "니어", c: "니어" },
  "behind": { n: "비하인드", c: "비하인드" },
  "across": { n: "어크로스", c: "어크로스" },
  "along": { n: "얼롱", c: "얼롱" },
  "away": { n: "어웨이", c: "어웨이" },
  "back": { n: "백", c: "백" },
  "or": { n: "오어", c: "오어" },
  "so": { n: "쏘우", c: "쏘우" },
  "at": { n: "앳", c: "앳" },
  "on": { n: "온", c: "온" },
  "in": { n: "인", c: "인" },
  "an": { n: "언", c: "앤" },
  "a": { n: "어", c: "어" },
  "the": { n: "더", c: "더" },
  "to": { n: "투", c: "투" },
  "for": { n: "포", c: "포" },
  "from": { n: "프롬", c: "프롬" },
  "with": { n: "위드", c: "위드" },
  "without": { n: "위드아웃", c: "위드아웃" },
  "of": { n: "오브", c: "오브" },
  "off": { n: "오프", c: "오프" },
  "up": { n: "업", c: "업" },
  "down": { n: "다운", c: "다운" },

  // 수식어
  "particularly": { n: "파티큘러리", c: "파티큘러리" },
  "particular": { n: "파티큘러", c: "파티큘러" },
  "fun": { n: "펀", c: "펀" },
  "funny": { n: "퍼니", c: "퍼니" },
  "interesting": { n: "인터레스팅", c: "인터레스팅" },
  "interested": { n: "인터레스티드", c: "인터레스티드" },
  "boring": { n: "보링", c: "보링" },
  "bored": { n: "보어드", c: "보어드" },
  "exciting": { n: "익사이팅", c: "익사이팅" },
  "excited": { n: "익사이티드", c: "익사이티드" },
  "good": { n: "굿", c: "굿" },
  "great": { n: "그레이트", c: "그레이트" },
  "nice": { n: "나이스", c: "나이스" },
  "awesome": { n: "오썸", c: "오썸" },
  "cool": { n: "쿨", c: "쿨" },
  "bad": { n: "배드", c: "배드" },
  "terrible": { n: "테러블", c: "테러블" },
  "happy": { n: "해피", c: "해피" },
  "sad": { n: "새드", c: "새드" },
  "tired": { n: "타이어드", c: "타이어드" },
  "busy": { n: "비지", c: "비지" },
  "really": { n: "리얼리", c: "리얼리" },
  "very": { n: "베리", c: "베리" },
  "much": { n: "머치", c: "머치" },
  "many": { n: "매니", c: "매니" },
  "too": { n: "투", c: "투" },
  "quite": { n: "콰이트", c: "콰이트" },
  "pretty": { n: "프리티", c: "프리티" },
  "especially": { n: "에스페셜리", c: "에스페셜리" },
  "actually": { n: "액츄얼리", c: "액츄얼리" },
  "definitely": { n: "데피니틀리", c: "데피니틀리" },
  "probably": { n: "프로버블리", c: "프로버블리" },
  "extremely": { n: "익스트림리", c: "익스트림리" },
  "completely": { n: "컴플리틀리", c: "컴플리틀리" },
  "always": { n: "올웨이즈", c: "올웨이즈" },
  "never": { n: "네버", c: "네버" },
  "sometimes": { n: "썸타임즈", c: "썸타임즈" },
  "often": { n: "오픈", c: "오픈" },
  "usually": { n: "유주얼리", c: "유주얼리" },
  "slowly": { n: "슬로울리", c: "슬로울리" },
  "quickly": { n: "퀴클리", c: "퀴클리" },
  "fast": { n: "패스트", c: "패스트" },
  "easy": { n: "이지", c: "이지" },
  "hard": { n: "하드", c: "하드" },
  "difficult": { n: "디피컬트", c: "디피컬트" },
  "simple": { n: "심플", c: "심플" },
  "big": { n: "빅", c: "빅" },
  "small": { n: "스몰", c: "스몰" },
  "hot": { n: "핫", c: "핫" },
  "cold": { n: "콜드", c: "콜드" },
  "warm": { n: "웜", c: "웜" },
  "cheap": { n: "칩", c: "칩" },
  "expensive": { n: "익스펜시브", c: "익스펜시브" },
  "delicious": { n: "딜리셔스", c: "딜리셔스" },
  "lot": { n: "랏", c: "랏" },
  "lots": { n: "랏츠", c: "랏츠" },
  "days": { n: "데이즈", c: "데이즈" },
  "years": { n: "이어즈", c: "이어즈" },
  "hours": { n: "아워즈", c: "아워즈" },
  "minutes": { n: "미닛츠", c: "미닛츠" },
  "weeks": { n: "위크스", c: "위크스" },
  "months": { n: "먼스스", c: "먼스스" },
  "times": { n: "타임즈", c: "타임즈" },
  "words": { n: "워즈", c: "워즈" },
  "word": { n: "워드", c: "워드" },
  "bit": { n: "빗", c: "비트" },
  "stuff": { n: "스터프", c: "스터프" },
  "ago": { n: "어고", c: "어고" },
  "yet": { n: "옛", c: "옛" },
  "anymore": { n: "애니모어", c: "애니모어" },
  "several": { n: "세버럴", c: "세버럴" },
  "whole": { n: "홀", c: "홀" },
  "huge": { n: "휴지", c: "휴지" },
  "tiny": { n: "타이니", c: "타이니" },
  "strong": { n: "스트롱", c: "스트롱" },
  "weak": { n: "위크", c: "위크" },
  "short": { n: "쇼트", c: "쇼트" },
  "tall": { n: "톨", c: "톨" },
  "deep": { n: "딥", c: "딥" },
  "wide": { n: "와이드", c: "와이드" },
  "narrow": { n: "내로우", c: "내로우" },
  "thick": { n: "씩", c: "씩" },
  "thin": { n: "씬", c: "씬" },
  "heavy": { n: "헤비", c: "헤비" },
  "light": { n: "라이트", c: "라이트" },
  "dark": { n: "다크", c: "다크" },
  "bright": { n: "브라이트", c: "브라이트" },
  "loud": { n: "라우드", c: "라우드" },
  "quiet": { n: "콰이엇", c: "콰이엇" },
  "soft": { n: "소프트", c: "소프트" },
  "rough": { n: "러프", c: "러프" },
  "smooth": { n: "스무드", c: "스무드" },
  "sweet": { n: "스윗", c: "스위트" },
  "sour": { n: "사워", c: "사워" },
  "salty": { n: "솔티", c: "솔티" },
  "spicy": { n: "스파이시", c: "스파이시" },
  "fresh": { n: "프레시", c: "프레시" },
  "safe": { n: "세이프", c: "세이프" },
  "dangerous": { n: "데인저러스", c: "데인저러스" },
  "far": { n: "파", c: "파" },
  "close": { n: "클로즈", c: "클로즈" },
  "popular": { n: "파퓰러", c: "파퓰러" },
  "famous": { n: "페이머스", c: "페이머스" },
  "rich": { n: "리치", c: "리치" },
  "poor": { n: "푸어", c: "푸어" },
  "lucky": { n: "럭키", c: "럭키" },
  "favorite": { n: "페이버릿", c: "페이버릿" },
  "normal": { n: "노멀", c: "노멀" },
  "strange": { n: "스트레인지", c: "스트레인지" },
  "crazy": { n: "크레이지", c: "크레이지" },
  "angry": { n: "앵그리", c: "앵그리" },
  "nervous": { n: "너버스", c: "너버스" },
  "worried": { n: "워리드", c: "워리드" },
  "scared": { n: "스케어드", c: "스케어드" },
  "surprised": { n: "서프라이즈드", c: "서프라이즈드" },
  "confused": { n: "컨퓨즈드", c: "컨퓨즈드" },
  "proud": { n: "프라우드", c: "프라우드" },
  "lovely": { n: "러블리", c: "러블리" },
  "cute": { n: "큐트", c: "큐트" },
  "ugly": { n: "어글리", c: "어글리" },
  "pretty": { n: "프리티", c: "프리티" },

  // 인사 & 매너 & 감탄사
  "please": { n: "플리즈", c: "플리즈" },
  "thank": { n: "땡크", c: "땡크" },
  "thanks": { n: "땡큐", c: "땡스" },
  "welcome": { n: "웰컴", c: "웰컴" },
  "hello": { n: "헬로우", c: "헬로우" },
  "hi": { n: "하이", c: "하이" },
  "hey": { n: "헤이", c: "헤이" },
  "bye": { n: "바이", c: "바이" },
  "goodbye": { n: "굿바이", c: "굿바이" },
  "sorry": { n: "쏘리", c: "쏘리" },
  "excuse": { n: "익스큐즈", c: "익스큐즈" },
  "pardon": { n: "파든", c: "파든" },
  "yes": { n: "예스", c: "예스" },
  "no": { n: "노", c: "노" },
  "okay": { n: "오케이", c: "오케이" },
  "ok": { n: "오케이", c: "오케이" },
  "sure": { n: "슈어", c: "슈어" },
  "right": { n: "롸잇", c: "라이트" },
  "alright": { n: "올라이트", c: "올라이트" },

  // 장소 & 여행
  "bathroom": { n: "배쓰룸", c: "배쓰룸" },
  "restroom": { n: "레스트룸", c: "레스트룸" },
  "toilet": { n: "토일렛", c: "토일렛" },
  "pharmacy": { n: "파머시", c: "파머시" },
  "drugstore": { n: "드럭스토어", c: "드럭스토어" },
  "hospital": { n: "하스피탈", c: "하스피탈" },
  "hotel": { n: "호텔", c: "호텔" },
  "airport": { n: "에어포트", c: "에어포트" },
  "station": { n: "스테이션", c: "스테이션" },
  "subway": { n: "서브웨이", c: "서브웨이" },
  "bus": { n: "버스", c: "버스" },
  "taxi": { n: "택시", c: "택시" },
  "train": { n: "트레인", c: "트레인" },
  "plane": { n: "플레인", c: "플레인" },
  "ticket": { n: "티켓", c: "티켓" },
  "passport": { n: "패스포트", c: "패스포트" },
  "bag": { n: "백", c: "백" },
  "luggage": { n: "러기지", c: "러기지" },
  "restaurant": { n: "레스토랑", c: "레스토랑" },
  "cafe": { n: "카페", c: "카페" },
  "menu": { n: "메뉴", c: "메뉴" },
  "bill": { n: "빌", c: "빌" },
  "water": { n: "워터", c: "워터" },
  "coffee": { n: "커피", c: "커피" },
  "cup": { n: "컵", c: "컵" },
  "glass": { n: "글래스", c: "글래스" },
  "bottle": { n: "보틀", c: "보틀" },
  "money": { n: "머니", c: "머니" },
  "dollar": { n: "달러", c: "달러" },
  "card": { n: "카드", c: "카드" },
  "cash": { n: "캐시", c: "캐시" },
  "today": { n: "투데이", c: "투데이" },
  "tomorrow": { n: "투모로우", c: "투모로우" },
  "yesterday": { n: "예스터데이", c: "예스터데이" },
  // 언어 & 번역 & 앱 관련 필수 단어
  "korea": { n: "코리아", c: "코리아" },
  "korean": { n: "코리안", c: "코리안" },
  "america": { n: "아메리카", c: "아메리카" },
  "american": { n: "아메리칸", c: "아메리칸" },
  "pronounce": { n: "프로나운스", c: "프로나운스" },
  "pronunciation": { n: "프로넌시에이션", c: "프로넌시에이션" },
  "translate": { n: "트랜슬레이트", c: "트랜슬레이트" },
  "translated": { n: "트랜슬레이티드", c: "트랜슬레이티드" },
  "translation": { n: "트랜슬레이션", c: "트랜슬레이션" },
  "translator": { n: "트랜슬레이터", c: "트랜슬레이터" },
  "language": { n: "랭귀지", c: "랭귀지" },
  "languages": { n: "랭귀지즈", c: "랭귀지즈" },
  "word": { n: "워드", c: "워드" },
  "words": { n: "워즈", c: "워즈" },
  "sentence": { n: "센턴스", c: "센턴스" },
  "sentences": { n: "센턴시즈", c: "센턴시즈" },
  "meaning": { n: "미닝", c: "미닝" },
  "meanings": { n: "미닝즈", c: "미닝즈" },
  "speak": { n: "스픽", c: "스픽" },
  "speaking": { n: "스피킹", c: "스피킹" },
  "say": { n: "세이", c: "세이" },
  "saying": { n: "세잉", c: "세잉" },
  "voice": { n: "보이스", c: "보이스" },
  "sound": { n: "사운드", c: "사운드" },
  "sounds": { n: "사운즈", c: "사운즈" },
  "listen": { n: "리슨", c: "리슨" },
  "listening": { n: "리스닝", c: "리스닝" },
  "hear": { n: "히어", c: "히어" },
  "hearing": { n: "히어링", c: "히어링" },
  "time": { n: "타임", c: "타임" },
  "minute": { n: "미닛", c: "미닛" },
  "hour": { n: "아워", c: "아워" },

  // ★★★ 추가 빈출 단어 (테스트 깨짐 해결) ★★★
  "problem": { n: "프라블럼", c: "프라블럼" },
  "problems": { n: "프라블럼즈", c: "프라블럼즈" },
  "english": { n: "잉글리시", c: "잉글리시" },
  "together": { n: "투게더", c: "투게더" },
  "been": { n: "빈", c: "빈" },
  "being": { n: "비잉", c: "비잉" },
  "find": { n: "파인드", c: "파인드" },
  "finding": { n: "파인딩", c: "파인딩" },
  "found": { n: "파운드", c: "파운드" },
  "there": { n: "데어", c: "데어" },
  "there's": { n: "데어즈", c: "데어 이즈" },
  "theres": { n: "데어즈", c: "데어 이즈" },
  "these": { n: "디즈", c: "디즈" },
  "those": { n: "도즈", c: "도즈" },
  "done": { n: "던", c: "던" },
  "gone": { n: "곤", c: "곤" },
  "taken": { n: "테이큰", c: "테이큰" },
  "given": { n: "기븐", c: "기븐" },
  "known": { n: "노운", c: "노운" },
  "shown": { n: "쇼운", c: "쇼운" },
  "seen": { n: "신", c: "신" },
  "gotten": { n: "가튼", c: "가튼" },
  "left": { n: "레프트", c: "레프트" },
  "told": { n: "톨드", c: "톨드" },
  "said": { n: "세드", c: "세드" },
  "called": { n: "콜드", c: "콜드" },
  "asked": { n: "애스크트", c: "애스크트" },
  "started": { n: "스타티드", c: "스타티드" },
  "stopped": { n: "스탑트", c: "스탑트" },
  "finished": { n: "피니시트", c: "피니시트" },
  "tried": { n: "트라이드", c: "트라이드" },
  "needed": { n: "니디드", c: "니디드" },
  "wanted": { n: "원티드", c: "원티드" },
  "used": { n: "유즈드", c: "유즈드" },
  "happened": { n: "해픈드", c: "해픈드" },
  "happen": { n: "해픈", c: "해픈" },
  "happens": { n: "해픈즈", c: "해픈즈" },
  "turn": { n: "턴", c: "턴" },
  "turning": { n: "터닝", c: "터닝" },
  "turned": { n: "턴드", c: "턴드" },
  "open": { n: "오픈", c: "오픈" },
  "close": { n: "클로즈", c: "클로즈" },
  "closed": { n: "클로즈드", c: "클로즈드" },
  "show": { n: "쇼우", c: "쇼우" },
  "showing": { n: "쇼잉", c: "쇼잉" },
  "pay": { n: "페이", c: "페이" },
  "paying": { n: "페잉", c: "페잉" },
  "paid": { n: "페이드", c: "페이드" },
  "buy": { n: "바이", c: "바이" },
  "buying": { n: "바잉", c: "바잉" },
  "bought": { n: "보트", c: "보트" },
  "sell": { n: "셀", c: "셀" },
  "sold": { n: "솔드", c: "솔드" },
  "eat": { n: "잇", c: "이트" },
  "eating": { n: "이팅", c: "이팅" },
  "ate": { n: "에이트", c: "에이트" },
  "eaten": { n: "이튼", c: "이튼" },
  "drink": { n: "드링크", c: "드링크" },
  "drinking": { n: "드링킹", c: "드링킹" },
  "sleep": { n: "슬립", c: "슬립" },
  "sleeping": { n: "슬리핑", c: "슬리핑" },
  "slept": { n: "슬렙트", c: "슬렙트" },
  "feel": { n: "필", c: "필" },
  "feeling": { n: "필링", c: "필링" },
  "felt": { n: "펠트", c: "펠트" },
  "hear": { n: "히어", c: "히어" },
  "hearing": { n: "히어링", c: "히어링" },
  "heard": { n: "허드", c: "허드" },
  "look": { n: "룩", c: "룩" },
  "looking": { n: "루킹", c: "루킹" },
  "looked": { n: "룩트", c: "룩트" },
  "watch": { n: "워치", c: "워치" },
  "watching": { n: "워칭", c: "워칭" },
  "wait": { n: "웨이트", c: "웨이트" },
  "waiting": { n: "웨이팅", c: "웨이팅" },
  "waited": { n: "웨이티드", c: "웨이티드" },
  "start": { n: "스타트", c: "스타트" },
  "starting": { n: "스타팅", c: "스타팅" },
  "stop": { n: "스탑", c: "스탑" },
  "stopping": { n: "스타핑", c: "스타핑" },
  "try": { n: "트라이", c: "트라이" },
  "trying": { n: "트라잉", c: "트라잉" },
  "use": { n: "유즈", c: "유즈" },
  "using": { n: "유징", c: "유징" },
  "ask": { n: "애스크", c: "애스크" },
  "asking": { n: "애스킹", c: "애스킹" },
  "answer": { n: "앤서", c: "앤서" },
  "help": { n: "헬프", c: "헬프" },
  "helping": { n: "헬핑", c: "헬핑" },
  "talk": { n: "토크", c: "토크" },
  "talking": { n: "토킹", c: "토킹" },
  "tell": { n: "텔", c: "텔" },
  "telling": { n: "텔링", c: "텔링" },
  "say": { n: "세이", c: "세이" },
  "saying": { n: "세잉", c: "세잉" },
  "speak": { n: "스픽", c: "스픽" },
  "speaking": { n: "스피킹", c: "스피킹" },
  "hope": { n: "호프", c: "호프" },
  "hoping": { n: "호핑", c: "호핑" },
  "wish": { n: "위시", c: "위시" },
  "believe": { n: "빌리브", c: "빌리브" },
  "need": { n: "니드", c: "니드" },
  "want": { n: "원트", c: "원트" },
  "knows": { n: "노우즈", c: "노우즈" },
  "does": { n: "더즈", c: "더즈" },
  "goes": { n: "고우즈", c: "고우즈" },
  "takes": { n: "테이크스", c: "테이크스" },
  "makes": { n: "메이크스", c: "메이크스" },
  "gives": { n: "기브즈", c: "기브즈" },
  "gets": { n: "게츠", c: "게츠" },
  "comes": { n: "커므즈", c: "커므즈" },
  "works": { n: "워크스", c: "워크스" },
  "seems": { n: "심즈", c: "심즈" },
  "looks": { n: "룩스", c: "룩스" },
  "feels": { n: "필즈", c: "필즈" },
  "means": { n: "민즈", c: "민즈" },
  "mean": { n: "민", c: "민" },

  // 추가 명사/형용사
  "school": { n: "스쿨", c: "스쿨" },
  "home": { n: "홈", c: "홈" },
  "house": { n: "하우스", c: "하우스" },
  "room": { n: "룸", c: "룸" },
  "door": { n: "도어", c: "도어" },
  "window": { n: "윈도우", c: "윈도우" },
  "table": { n: "테이블", c: "테이블" },
  "chair": { n: "체어", c: "체어" },
  "book": { n: "북", c: "북" },
  "phone": { n: "폰", c: "폰" },
  "computer": { n: "컴퓨터", c: "컴퓨터" },
  "car": { n: "카", c: "카" },
  "street": { n: "스트리트", c: "스트리트" },
  "road": { n: "로드", c: "로드" },
  "city": { n: "시티", c: "시티" },
  "country": { n: "컨트리", c: "컨트리" },
  "food": { n: "푸드", c: "푸드" },
  "family": { n: "패밀리", c: "패밀리" },
  "friend": { n: "프렌드", c: "프렌드" },
  "friends": { n: "프렌즈", c: "프렌즈" },
  "child": { n: "차일드", c: "차일드" },
  "children": { n: "칠드런", c: "칠드런" },
  "man": { n: "맨", c: "맨" },
  "woman": { n: "우먼", c: "우먼" },
  "boy": { n: "보이", c: "보이" },
  "girl": { n: "걸", c: "걸" },
  "baby": { n: "베이비", c: "베이비" },
  "brother": { n: "브라더", c: "브라더" },
  "sister": { n: "시스터", c: "시스터" },
  "mother": { n: "마더", c: "마더" },
  "father": { n: "파더", c: "파더" },
  "mom": { n: "맘", c: "맘" },
  "dad": { n: "대드", c: "대드" },
  "beautiful": { n: "뷰티풀", c: "뷔티풀" },
  "wonderful": { n: "원더풀", c: "원더풀" },
  "perfect": { n: "퍼펙트", c: "퍼펙트" },
  "important": { n: "임포턴트", c: "임포턴트" },
  "possible": { n: "파서블", c: "파서블" },
  "impossible": { n: "임파서블", c: "임파서블" },
  "careful": { n: "케어풀", c: "케어풀" },
  "sure": { n: "슈어", c: "슈어" },
  "ready": { n: "레디", c: "레디" },
  "able": { n: "에이블", c: "에이블" },
  "special": { n: "스페셜", c: "스페셜" },
  "free": { n: "프리", c: "프리" },
  "true": { n: "트루", c: "트루" },
  "false": { n: "폴스", c: "폴스" },
  "wrong": { n: "롱", c: "롱" },
  "late": { n: "레이트", c: "레이트" },
  "early": { n: "얼리", c: "얼리" },
  "full": { n: "풀", c: "풀" },
  "empty": { n: "엠프티", c: "엠프티" },
  "clean": { n: "클린", c: "클린" },
  "clear": { n: "클리어", c: "클리어" },
  "nice": { n: "나이스", c: "나이스" },
  "kind": { n: "카인드", c: "카인드" },
  "sick": { n: "시크", c: "시크" },
  "fine": { n: "파인", c: "파인" },
  "well": { n: "웰", c: "웰" },
  "own": { n: "오운", c: "오운" },
  "real": { n: "리얼", c: "리얼" },
  "certain": { n: "서튼", c: "서튼" },
  "whole": { n: "홀", c: "홀" },

  // 숫자
  "one": { n: "원", c: "원" },
  "two": { n: "투", c: "투" },
  "three": { n: "쓰리", c: "쓰리" },
  "four": { n: "포", c: "포" },
  "five": { n: "파이브", c: "파이브" },
  "six": { n: "식스", c: "식스" },
  "seven": { n: "세븐", c: "세븐" },
  "eight": { n: "에이트", c: "에이트" },
  "nine": { n: "나인", c: "나인" },
  "ten": { n: "텐", c: "텐" },
  "hundred": { n: "헌드레드", c: "헌드레드" },
  "thousand": { n: "따우전드", c: "따우전드" },

  // 추가 기본 단어
  "now": { n: "나우", c: "나우" },
  "here": { n: "히어", c: "히어" },
  "able": { n: "에이블", c: "에이블" },
  "each": { n: "이치", c: "이치" },
  "either": { n: "이더", c: "이더" },
  "neither": { n: "니더", c: "니더" },
  "such": { n: "서치", c: "서치" },
  "own": { n: "오운", c: "오운" },
  "quite": { n: "콰이트", c: "콰이트" },
  "rather": { n: "래더", c: "래더" },
  "however": { n: "하우에버", c: "하우에버" },
  "although": { n: "올도우", c: "올도우" },
  "whether": { n: "웨더", c: "웨더" },
  "else": { n: "엘스", c: "엘스" },
  "except": { n: "익셉트", c: "익셉트" },
  "instead": { n: "인스테드", c: "인스테드" },
  "might": { n: "마이트", c: "마이트" },
  "shall": { n: "쉘", c: "쉘" },
  "must": { n: "머스트", c: "머스트" },
  "almost": { n: "올모스트", c: "올모스트" },
  "soon": { n: "순", c: "순" },
  "later": { n: "레이터", c: "레이터" },
  "ever": { n: "에버", c: "에버" },
  "anymore": { n: "애니모어", c: "애니모어" },
  "outside": { n: "아웃사이드", c: "아웃사이드" },
  "inside": { n: "인사이드", c: "인사이드" },
  "above": { n: "어버브", c: "어버브" },
  "below": { n: "빌로우", c: "빌로우" },
  "cost": { n: "코스트", c: "코스트" },
  "price": { n: "프라이스", c: "프라이스" },
  "story": { n: "스토리", c: "스토리" },
  "movie": { n: "무비", c: "무비" },
  "music": { n: "뮤직", c: "뮤직" },
  "game": { n: "게임", c: "게임" },
  "idea": { n: "아이디어", c: "아이디어" },
  "question": { n: "퀘스천", c: "퀘스천" },
  "morning": { n: "모닝", c: "모닝" },
  "night": { n: "나이트", c: "나이트" },
  "today": { n: "투데이", c: "투데이" },
  "tonight": { n: "투나이트", c: "투나이트" },
  "day": { n: "데이", c: "데이" },
  "week": { n: "위크", c: "위크" },
  "month": { n: "먼스", c: "먼스" },
  "head": { n: "헤드", c: "헤드" },
  "hand": { n: "핸드", c: "핸드" },
  "eye": { n: "아이", c: "아이" },
  "face": { n: "페이스", c: "페이스" },
  "body": { n: "바디", c: "바디" },
  "heart": { n: "하트", c: "하트" },
  "mind": { n: "마인드", c: "마인드" },
  "side": { n: "사이드", c: "사이드" },
  "part": { n: "파트", c: "파트" },
  "end": { n: "엔드", c: "엔드" },
  "point": { n: "포인트", c: "포인트" },
  "number": { n: "넘버", c: "넘버" },
  "fact": { n: "팩트", c: "팩트" },
  "case": { n: "케이스", c: "케이스" },
  "class": { n: "클래스", c: "클래스" },
  "group": { n: "그룹", c: "그룹" },
  "team": { n: "팀", c: "팀" },
  "job": { n: "잡", c: "잡" },
  "power": { n: "파워", c: "파워" },
  "line": { n: "라인", c: "라인" },
  "reason": { n: "리즌", c: "리즌" },
  "course": { n: "코스", c: "코스" },
  "company": { n: "컴퍼니", c: "컴퍼니" },
  "weather": { n: "웨더", c: "웨더" },
  "season": { n: "시즌", c: "시즌" },
  "spring": { n: "스프링", c: "스프링" },
  "summer": { n: "썸머", c: "썸머" },
  "fall": { n: "폴", c: "폴" },
  "winter": { n: "윈터", c: "윈터" },
  "rain": { n: "레인", c: "레인" },
  "snow": { n: "스노우", c: "스노우" },
  "sun": { n: "선", c: "선" },
  "color": { n: "컬러", c: "컬러" },
  "size": { n: "사이즈", c: "사이즈" },
  "clothes": { n: "클로즈", c: "클로즈" },
  "shoes": { n: "슈즈", c: "슈즈" },
  "shirt": { n: "셔츠", c: "셔츠" },
  "hat": { n: "햇", c: "햇" },
  "photo": { n: "포토", c: "포토" },
  "picture": { n: "픽처", c: "픽처" },
  "garden": { n: "가든", c: "가든" },
  "kitchen": { n: "키친", c: "키친" },
  "market": { n: "마켓", c: "마켓" },
  "store": { n: "스토어", c: "스토어" },
  "shop": { n: "샵", c: "샵" },
  "shopping": { n: "쇼핑", c: "쇼핑" },
  "park": { n: "파크", c: "파크" },
  "beach": { n: "비치", c: "비치" },
  "movie": { n: "무비", c: "무비" },
  "music": { n: "뮤직", c: "뮤직" },
  "dance": { n: "댄스", c: "댄스" },
  "song": { n: "송", c: "송" },
  "birthday": { n: "버스데이", c: "버스데이" },
  "party": { n: "파티", c: "파티" },
  "holiday": { n: "홀리데이", c: "홀리데이" },
  "vacation": { n: "베이케이션", c: "베이케이션" },
  "trip": { n: "트립", c: "트립" },
  "travel": { n: "트래블", c: "트래블" }
};

// 2. 실전 원어민 연음(Liaison) 규칙 목록
const LIAISON_LIST = [
  // 사용자가 질문한 문장 맞춤형 연음
  { p: /\bhard at making an app right now\b/gi, n: "하댓 메이킹 어냅 롸잇 나우", c: "하드 앳 메이킹 앤 앱 라이트 나우" },
  { p: /\bhard at making\b/gi, n: "하댓 메이킹", c: "하드 앳 메이킹" },
  { p: /\bhard at\b/gi, n: "하댓", c: "하드 앳" },
  { p: /\bmaking an app\b/gi, n: "메이킹 어냅", c: "메이킹 앤 앱" },
  { p: /\bmaking an\b/gi, n: "메이킹 언", c: "메이킹 앤" },
  { p: /\ban app\b/gi, n: "어냅", c: "앤 앱" },
  { p: /\bright now\b/gi, n: "롸잇 나우", c: "라이트 나우" },
  { p: /\bbut it's not going well\b/gi, n: "버릿츠 낫 고잉 웰", c: "벗 잇츠 낫 고잉 웰" },
  { p: /\bbut it's\b/gi, n: "버릿츠", c: "벗 잇츠" },
  { p: /\bbut it is\b/gi, n: "버리리즈", c: "벗 잇 이즈" },
  { p: /\bnot going well\b/gi, n: "낫 고잉 웰", c: "낫 고잉 웰" },

  // 일반 회화 연음 규칙
  { p: /\bit's not particularly fun\b/gi, n: "잇츠 낫 파티큘러리 펀", c: "잇 이즈 낫 파티큘러리 펀" },
  { p: /\bwhere is the bathroom\b/gi, n: "웨얼 이즈 더 배쓰룸", c: "웨어 이즈 더 배쓰룸" },
  { p: /\bwhere is the\b/gi, n: "웨얼 이즈 더", c: "웨어 이즈 더" },
  { p: /\bwhere are you\b/gi, n: "웨어라유", c: "웨어 아 유" },
  { p: /\bwhat are you doing\b/gi, n: "와라유 두잉", c: "왓 아 유 두잉" },
  { p: /\bwhat are you\b/gi, n: "와라유", c: "왓 아 유" },
  { p: /\bwhat do you mean\b/gi, n: "왓 두 유 민", c: "왓 두 유 민" },
  { p: /\bhow much is it\b/gi, n: "하우 머치 이짓", c: "하우 머치 이즈 잇" },
  { p: /\bhow much is this\b/gi, n: "하우 머치 이즈 디스", c: "하우 머치 이즈 디스" },
  { p: /\bhow much does it cost\b/gi, n: "하우 머치 더짓 코스트", c: "하우 머치 더즈 잇 코스트" },
  { p: /\bcan i have a cup of coffee\b/gi, n: "캐나이 해브 어 컵 오브 커피", c: "캔 아이 해브 어 컵 오브 커피" },
  { p: /\bcan i have\b/gi, n: "캐나이 해브", c: "캔 아이 해브" },
  { p: /\bcan i get\b/gi, n: "캐나이 겟", c: "캔 아이 겟" },
  { p: /\bcan i try this on\b/gi, n: "캐나이 트라이 디스 온", c: "캔 아이 트라이 디스 온" },
  { p: /\bcould you help me\b/gi, n: "쿠쥬 헬프 미", c: "쿠드 유 헬프 미" },
  { p: /\bwould you like\b/gi, n: "우쥬 라이크", c: "우드 유 라이크" },
  { p: /\bnice to meet you\b/gi, n: "나이스 투 미츄", c: "나이스 투 미트 유" },
  { p: /\bthank you so much\b/gi, n: "땡큐 쏘우 머치", c: "땡큐 쏘우 머치" },
  { p: /\bthank you\b/gi, n: "땡큐", c: "땡큐" },
  { p: /\byou're welcome\b/gi, n: "유어 웰컴", c: "유어 웰컴" },
  { p: /\bexcuse me\b/gi, n: "익스큐즈 미", c: "익스큐즈 미" },
  { p: /\bi don't know\b/gi, n: "아이 돈 노우", c: "아이 돈트 노우" },
  { p: /\bcheck in\b/gi, n: "체킨", c: "체크 인" },
  { p: /\bcheck out\b/gi, n: "체카웃", c: "체크 아웃" },
  { p: /\bdrop me off\b/gi, n: "드랍 미 오프", c: "드롭 미 오프" },
  { p: /\bwork out\b/gi, n: "워크 아웃", c: "워크 아웃" },
  { p: /\bworks out\b/gi, n: "워크스 아웃", c: "워크스 아웃" },
  { p: /\bdoesn't work\b/gi, n: "더즌 워크", c: "더즌트 워크" },
  { p: /\bdoesn't\b/gi, n: "더즌트", c: "더즈 낫" },
  { p: /\bfigure out\b/gi, n: "피겨 아웃", c: "피겨 아웃" },
  { p: /\bfind out\b/gi, n: "파인 다웃", c: "파인드 아웃" },
  { p: /\bturn out\b/gi, n: "턴 아웃", c: "턴 아웃" },
  { p: /\bget out\b/gi, n: "게라웃", c: "겟 아웃" },
  { p: /\bgo out\b/gi, n: "고 아웃", c: "고 아웃" },
  { p: /\bhang out\b/gi, n: "행 아웃", c: "행 아웃" },
  { p: /\bcome on\b/gi, n: "커먼", c: "컴 온" },
  { p: /\bhold on\b/gi, n: "홀 돈", c: "홀드 온" },
  { p: /\bgive up\b/gi, n: "기법", c: "기브 업" },
  { p: /\bpick up\b/gi, n: "피컵", c: "픽 업" },
  { p: /\bwake up\b/gi, n: "웨이컵", c: "웨이크 업" },
  { p: /\bhard on\b/gi, n: "하든", c: "하드 온" }
];

// 한글 조합 테이블
const CHO_ARR = ['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];
const JUNG_ARR = ['ㅏ','ㅐ','ㅑ','ㅒ','ㅓ','ㅔ','ㅕ','ㅖ','ㅗ','ㅘ','ㅙ','ㅚ','ㅛ','ㅜ','ㅝ','ㅞ','ㅟ','ㅠ','ㅡ','ㅢ','ㅣ'];
const JONG_ARR = ['','ㄱ','ㄲ','ㄳ','ㄴ','ㄵ','ㄶ','ㄷ','ㄹ','ㄺ','ㄻ','ㄼ','ㄽ','ㄾ','ㄿ','ㅀ','ㅁ','ㅂ','ㅄ','ㅅ','ㅆ','ㅇ','ㅈ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];

function makeHangul(cho, jung, jong = '') {
  const c = CHO_ARR.indexOf(cho);
  const u = JUNG_ARR.indexOf(jung);
  const j = JONG_ARR.indexOf(jong);
  if (c === -1 || u === -1) return (cho || '') + (jung || '') + (jong || '');
  return String.fromCharCode(0xAC00 + (c * 21 + u) * 28 + (j === -1 ? 0 : j));
}

/**
 * 사전에 없는 단어 안전 파싱 (음절 패턴 기반)
 */
function parseFallback(word, mode) {
  let w = word.toLowerCase().trim();
  if (!w) return "";

  // 접미사 분리 처리
  const suffixes = [
    { pat: /^(.{2,})ing$/,  fn: (r) => convertWord(r, mode) + "잉" },
    { pat: /^(.{2,})tion$/, fn: (r) => convertWord(r, mode) + "션" },
    { pat: /^(.{2,})sion$/, fn: (r) => convertWord(r, mode) + "션" },
    { pat: /^(.{2,})ness$/, fn: (r) => convertWord(r, mode) + "니스" },
    { pat: /^(.{2,})ment$/, fn: (r) => convertWord(r, mode) + "먼트" },
    { pat: /^(.{2,})able$/, fn: (r) => convertWord(r, mode) + "어블" },
    { pat: /^(.{2,})ible$/, fn: (r) => convertWord(r, mode) + "이블" },
    { pat: /^(.{2,})ful$/,  fn: (r) => convertWord(r, mode) + "풀" },
    { pat: /^(.{2,})less$/, fn: (r) => convertWord(r, mode) + "리스" },
    { pat: /^(.{2,})ly$/,   fn: (r) => convertWord(r, mode) + "리" },
    { pat: /^(.{2,})ed$/,   fn: (r) => convertWord(r, mode) + "드" },
    { pat: /^(.{2,})er$/,   fn: (r) => convertWord(r, mode) + "어" },
    { pat: /^(.{2,})est$/,  fn: (r) => convertWord(r, mode) + "이스트" },
    { pat: /^(.{2,})es$/,   fn: (r) => convertWord(r, mode) + "즈" },
    { pat: /^(.{2,})s$/,    fn: (r) => { const rc = convertWord(r, mode); return rc !== r ? rc + "스" : null; } },
  ];

  for (const sf of suffixes) {
    const m = w.match(sf.pat);
    if (m) {
      const root = m[1];
      // 루트가 사전에 있으면 접미사 분리
      if (PHONETIC_DB[root]) {
        const result = sf.fn(root);
        if (result) return result;
      }
    }
  }

  // 음절 청크 매핑 (긴 패턴 우선)
  const CHUNK_MAP = [
    // 5글자+
    ["night", "나이트"], ["light", "라이트"], ["right", "라이트"], ["sight", "사이트"],
    ["fight", "파이트"], ["might", "마이트"], ["tight", "타이트"],
    ["ough", "오우"], ["ould", "우드"], ["ound", "아운드"],
    // 4글자
    ["tion", "션"], ["sion", "션"], ["ight", "아이트"],
    ["ough", "어프"], ["atch", "애치"], ["etch", "에치"], ["itch", "이치"],
    ["each", "이치"], ["ouch", "아우치"], ["ious", "이어스"],
    ["eous", "이어스"], ["ture", "처"], ["sure", "셔"],
    ["ance", "언스"], ["ence", "언스"], ["able", "에이블"], ["ible", "이블"],
    ["ness", "니스"], ["ment", "먼트"], ["less", "리스"],
    ["ally", "얼리"], ["ully", "울리"], ["ious", "이어스"],
    // 3글자
    ["igh", "아이"], ["ght", "트"], ["tch", "치"],
    ["air", "에어"], ["ear", "이어"], ["our", "아워"],
    ["oor", "우어"], ["eer", "이어"],
    ["all", "올"], ["alk", "오크"], ["alt", "올트"],
    ["ong", "옹"], ["ang", "앵"], ["ing", "잉"], ["ung", "엉"],
    ["ank", "앵크"], ["ink", "잉크"], ["unk", "엉크"],
    ["and", "앤드"], ["end", "엔드"], ["ind", "아인드"], ["ond", "온드"],
    ["ard", "아드"], ["ord", "오드"], ["ird", "어드"],
    ["ark", "아크"], ["ork", "오크"], ["irk", "어크"],
    ["arm", "암"], ["orm", "옴"], ["erm", "엄"],
    ["arn", "안"], ["orn", "온"], ["urn", "언"],
    ["art", "아트"], ["ort", "오트"], ["irt", "어트"],
    ["ast", "애스트"], ["ost", "오스트"], ["ist", "이스트"], ["ust", "어스트"],
    ["ade", "에이드"], ["age", "에이지"], ["ake", "에이크"], ["ale", "에일"],
    ["ame", "에임"], ["ane", "에인"], ["ape", "에이프"], ["are", "에어"],
    ["ate", "에이트"], ["ave", "에이브"], ["aze", "에이즈"],
    ["ide", "아이드"], ["ife", "아이프"], ["ike", "아이크"], ["ile", "아일"],
    ["ime", "아임"], ["ine", "아인"], ["ipe", "아이프"], ["ire", "아이어"],
    ["ise", "아이즈"], ["ite", "아이트"], ["ive", "아이브"],
    ["obe", "오브"], ["ode", "오드"], ["oke", "오크"], ["ole", "올"],
    ["ome", "옴"], ["one", "원"], ["ope", "오프"], ["ore", "오어"],
    ["ose", "오즈"], ["ote", "오트"], ["ove", "오브"],
    ["ube", "유브"], ["ude", "유드"], ["uke", "유크"], ["ule", "율"],
    ["ume", "유뮴"], ["une", "유운"], ["upe", "유프"], ["ure", "유어"],
    ["use", "유즈"], ["ute", "유트"],
    ["ack", "액"], ["eck", "에크"], ["ick", "이크"], ["ock", "옥"], ["uck", "억"],
    ["ash", "애시"], ["ush", "어시"], ["ish", "이시"],
    ["ess", "에스"], ["oss", "오스"], ["ass", "애스"], ["uss", "어스"],
    ["ell", "엘"], ["ill", "일"], ["oll", "올"], ["ull", "울"],
    ["aw", "오"], ["ew", "유"], ["ow", "오우"],
    // 2글자 다이그래프
    ["ph", "프"], ["sh", "쉬"], ["ch", "치"], ["th", "드"],
    ["wh", "우"], ["wr", "르"], ["kn", "느"], ["gn", "느"],
    ["qu", "쿠"], ["ck", "크"], ["ng", "응"], ["nk", "응크"],
    ["ai", "에이"], ["ay", "에이"], ["ei", "에이"], ["ey", "에이"],
    ["oi", "오이"], ["oy", "오이"],
    ["ou", "아우"], ["ow", "아우"],
    ["oo", "우"], ["ee", "이"], ["ea", "이"],
    ["ie", "아이"], ["ue", "유"],
    ["ar", "아"], ["er", "어"], ["ir", "어"], ["or", "오"], ["ur", "어"],
    ["al", "올"], ["el", "엘"], ["il", "일"], ["ol", "올"], ["ul", "울"],
    // 1글자 자음
    ["b", "브"], ["c", "크"], ["d", "드"], ["f", "프"],
    ["g", "그"], ["h", "흐"], ["j", "제이"], ["k", "크"],
    ["l", "ㄹ"], ["m", "므"], ["n", "느"], ["p", "프"],
    ["r", "르"], ["s", "스"], ["t", "트"], ["v", "브"],
    ["w", "우"], ["x", "크스"], ["y", "이"], ["z", "즈"],
    // 1글자 모음
    ["a", "아"], ["e", "에"], ["i", "이"], ["o", "오"], ["u", "어"],
  ];

  let result = "";
  let i = 0;
  while (i < w.length) {
    let matched = false;
    // 긴 패턴부터 매치 시도
    for (const [pat, hangul] of CHUNK_MAP) {
      if (w.startsWith(pat, i)) {
        result += hangul;
        i += pat.length;
        matched = true;
        break;
      }
    }
    if (!matched) {
      result += w[i]; // 숫자나 특수문자는 그대로
      i++;
    }
  }

  // 후처리: 연속 자음 정리
  result = result
    .replace(/스스/g, "스")
    .replace(/트트/g, "트")
    .replace(/크크/g, "크")
    .replace(/프프/g, "프")
    .replace(/ㄹ([가-힣])/g, "ㄹ$1") // ㄹ + 한글 조합 유지
    .replace(/ㄹ/g, "르"); // 단독 ㄹ → 르

  return result;
}

/**
 * 단어 단위 변환
 */
function convertWord(word, mode = 'natural') {
  if (!word) return "";
  // 둥근 따옴표(’/‘) 및 하이픈(-) 포함하여 단어 분리
  const match = word.match(/^([^a-zA-Z0-9'’\-]*)([a-zA-Z0-9'’\-]+)([^a-zA-Z0-9'’\-]*)$/);
  if (!match) return word;

  const prefix = match[1] || "";
  const core = match[2];
  const suffix = match[3] || "";
  
  // 둥근 따옴표를 일반 따옴표로 변환하여 소문자로 비교
  const lower = core.replace(/[’‘]/g, "'").toLowerCase();

  let korean = "";
  if (PHONETIC_DB[lower]) {
    korean = (mode === 'clear' ? PHONETIC_DB[lower].c : PHONETIC_DB[lower].n);
  } else {
    korean = parseFallback(lower, mode);
  }

  return prefix + korean + suffix;
}

/**
 * 메인 영어 -> 한글 발음(독음) 변환
 * @param {string} text 
 * @param {string} mode 'natural' (원어민 연음) | 'clear' (또박또박)
 */
function englishToKoreanPhonetics(text, mode = 'natural') {
  if (!text || typeof text !== "string") return "";

  let working = text.trim();

  // 1. 연음 규칙 우선 치환
  for (const item of LIAISON_LIST) {
    const rep = (mode === 'clear' ? item.c : item.n);
    working = working.replace(item.p, `§§${rep}§§`);
  }

  // 2. 단어별 변환
  const parts = working.split(/(§§[^§]+§§)/g);
  const results = parts.map(part => {
    if (part.startsWith("§§") && part.endsWith("§§")) {
      return part.slice(2, -2);
    }
    const words = part.split(/(\s+)/);
    return words.map(w => {
      if (/^\s+$/.test(w)) return w;
      return convertWord(w, mode);
    }).join("");
  });

  let final = results.join("").replace(/\s+/g, " ").trim();

  // 구두점 정리
  final = final
    .replace(/ \?/g, "?")
    .replace(/ \!/g, "!")
    .replace(/ \./g, ".")
    .replace(/ \,/g, ",");

  return final;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { englishToKoreanPhonetics, convertWord, PHONETIC_DB, LIAISON_LIST };
}
